import { authLabel } from '@data/localization/common/auth'
import useLang from '@hooks/useLang'
import Button from '@ui/common/atoms/Button'
import InputField from '@ui/common/atoms/InputField'
import Label from '@ui/common/atoms/Lable'
import {Link,UseNavigation} from 'react-router-dom'